name: ROS 2 CI

on:
  push:
    branches: [feature/cicd]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        #stores github workspace in $GITHUB_WORKSPACE

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          distribution: jazzy  # or foxy, iron, etc.

      - name: Create workspace and move repo
        run: |
          echo $GITHUB_WORKSPACE
          whoami
          mkdir -p ~/ros2_ws/src/mdriver
          mv * ~/ros2_ws/src/mdriver
          mv .github ~/ros2_ws/src/mdriver
          cd ~/ros2_ws
          ls -la src
          echo $PWD

      - name: Install dependencies
        run: |
          sudo apt update
          rosdep update
          rosdep install --from-paths ./src --ignore-src -r -y

      - name: Build the workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_direct+

#      - name: Run tests
#        run: |
#          cd ros2_ws
#          source install/setup.bash
#          colcon test
#          colcon test-result --verbose
